service: packaging_test

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.6
  region: eu-central-1

package:
  individually: true
  exclude:
    - '**/*'

functions:
  function-one:
    handler: main.handler
    module: ./fn
    package:
      include:
        - 'fn/**'
  function-one-and-a-half:
    handler: main.handler2
    module: fn
    package:
      include:
        - 'fn/**'
  function-two:
    handler: main.handler
    module: fn2
    package:
      include:
        - 'fn2/**'
