service: packaging_test

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.6
  region: eu-central-1

package:
  individually: true
  exclude:
    - '**/*'
  include:
    - 'fn/**'

functions:
  function-one:
    handler: main.handler
    module: fn
    vendor: ./vendor
  function-two:
    handler: main.handler
    module: fn
    vendor: ./vendor2
